#!/bin/bash

############################################################
# check_time
#
# Checks time against external server and adjusts if
# deviation is greater than $deltamax
#
# WS 20110702
############################################################
########## Changes ##########
####
# Added root check, removed service restart
# WS 20111013
####


########### Configure here ###########
# Limit for time deviation
delta_max=300
# Time server
server=0.de.pool.ntp.org
######### Configuration end ##########

rc=0
delta=

if [[ "$(id -u)" != 0 ]]; then
	echo "This script must be run as root" >&2
	exit 1
fi


# Get time delta from external server
delta=$(ntpdate -q $server 2> /dev/null | awk '/adjust/ {gsub(/[-+]/,""); if ($(NF-1)~/^[0-9]+\.*[0-9]*$/) {print int($(NF-1))}}')

if [[ -z "$delta" ]]; then
	echo "Error: No time server could be reached" >&2
	exit 1
else
	# If time delta grater than $delta_max, adjust time
	if [[ $delta -ge $delta_max ]]; then
		if ! sntp -K /dev/null -s $server &> /dev/null; then
			echo "Could not set time" >&2
			exit 1
		fi
	fi
	
fi

exit 0

# EOF
