#!/bin/sh

##################################################
# countlines
#
# Count code lines in shell scripts
# 
# WS 20050507
##################################################
########## Changes ##########
####
# Pruned unnecessary "wc", improved error handling
# WS 20110414
####


usage()
{
cat << END

"`basename $0`" counts code lines in a given script

Usage: `basename $0` <script_file>

END
}

# Error handling
if [ $# -ne 1 ]; then
	echo "No or to many parameters" 1>&2
	usage 1>&2
	exit 2
else
	file=$1
fi

if [ ! -f $file ]; then
	echo "Could not find \"${file}\"" 1>&2
	usage 1>&2
fi

## Here we go
# Count all lines
allines=`wc -l $file | cut -d' ' -f 1`
# Count only non-empty lines not beginning with "#"
codelines=`awk 'BEGIN {n=0} !/[\/s][\/s]*$/ && !/[\/s]*#/ && !/^$/ {n++} END {print n}' $file` 2> /dev/null

if [ -z $codelines -o $codelines -le 0 ] 2> /dev/null; then
	echo "Could not find any code line in $file" 1>&2
	exit 1
fi

echo "The script \"$file\" has $allines lines from which $codelines lines are code"

exit 0

# EOF
