#!/bin/bash

##################################################
# countlines
#
# Count code lines in shell scripts
# 
# WS 20050507
##################################################
########## Changes ##########
####
# Pruned unnecessary "wc", improved error handling
# WS 20110414
####
####
# sh -> bash, cleared awk expression
# WS 20111013
####


usage() {
cat <<END

"${0##*/}" counts code lines in a given script

Usage: ${0##*/} <script_file>

END
}

# Error handling
if [[ $# != 1 ]]; then
	echo "No or to many parameters" >&2
	usage >&2
	exit 2
else
	FILE=$1
fi

if [[ ! -f "$FILE" ]]; then
	echo "Could not find \"${FILE}\"" >&2
	usage >&2
fi

## Here we go
# Count all lines
ALLINES=$(wc -l $FILE | cut -d' ' -f 1)
# Count only non-empty lines not beginning with "#"
CODELINES=$(awk 'BEGIN {n=0} !/^[[:space:]]*$/ && !/^[[:space:]]*#/ {n++} END {print n}' $FILE) 2> /dev/null

if [[ -z "$CODELINES" || $CODELINES -le 0 ]]; then
	echo "Could not find any code line in $FILE" >&2
	exit 1
fi

echo "The script \"$FILE\" has $ALLINES lines from which $CODELINES lines are code"

exit 0

# EOF
