#!/bin/bash

################################################################################
# deviceinfo
#
# Print udev informations about a given device
# Tested on Fedora 14, Ubuntu 10.10, Red Hat EL/CentOS 5.5, SLES 11
#
# WS 20110420
################################################################################
########## Changes ##########
####
# Changed order of udevadm/udevinfo detection for SLES
# WS 20111110

RC=0
DEVICE=
QUERY=

usage() {
local BASENAME=${0##*/}
cat << END

"$BASENAME" prints udev informations about a given device

Usage:   $BASENAME <device>
Example: $BASENAME /dev/sda

If the device name doesn't start with "/dev/" it will automatically prefixed with "/dev/"
END
}

# We will process only one parameter
if [[ $# != 1 ]]; then
	usage >&2
	exit 1
else
	DEVICE=$1
fi

# If the device doesn't start with "/dev/" prefix it with "/dev/"
if grep -qv '^/dev/' <<<$DEVICE; then
	DEVICE=${DEVICE/#/\/dev\/}
fi

# Does the device exist?
if [[ ! -e $DEVICE ]]; then
	echo "Error: Could not find $DEVICE" >&2
	exit 2
fi


# Get device info with either "udevinfo" or "udevadm"
if QUERY=$(which udevadm 2> /dev/null); then
	$QUERY info --attribute-walk --name=$DEVICE 
	RC=$?
else
	if QUERY=$(which udevinfo 2> /dev/null); then
		$QUERY -a -p $(udevinfo -q path -n $DEVICE)
		RC=$?
	else
		echo "Error: Couldn't find udevadm or udevinfo in path" >&2
		exit 2
	fi
fi

RC=$((RC+$?))

if [[ $RC != 1 ]]; then
	RC=1
fi

exit $RC

# EOF
