#!/bin/bash

############################################################
# getextip_web
# Obtains external IP address via Internet
#
# WS 20110326
############################################################
########## Changes ##########
####
# Errors are printed to stderr now
# WS 20110407
####
# Made the script more portable, it uses either wget or curl
# and takes into account different versions of awk (can be run
# on a Mac now)
# WS 20110418
####
# Used showip.net instead of dyndns.org because dyndns.org
# returns the local instead of the external IP address when
# using a proxy
# WS 20110420
####


AWK=
CURL=
WGET=
GET=
IP_ADDRESS=
IP_TEST=

# Look for awk
if AWK=$(which awk 2>/dev/null); then
	# If we have the GNU version, we need --reinterval
	if $AWK --version 2>/dev/null | grep -q GNU; then
		AWK="$AWK --re-interval"
	fi 
else
	echo "Could not find GNU awk, bailing out." >&2
	exit 1
fi

# Look for wget or curl
if WGET=$(which wget 2>/dev/null); then
	GET="$WGET --no-cache -q -O - -t 1 -T 10"
else
	if CURL=$(which curl 2>/dev/null); then
		GET="$CURL -s --retry 1 --connect-timeout 10"
	else
		echo "Could not find wget or curl, bailing out." >&2
		exit 1
	fi
fi

#### Here we go
# Get IP address
if IP_ADDRESS=$($GET http://showip.net/ 2>/dev/null); then
	# Extract IP address from HTML
	IP_ADDRESS=$(awk -F\" '/check_ip/ && /value=/ {print $(NF-1)}'<<<"$IP_ADDRESS")
else
	if IP_ADDRESS=$($GET http://www.whatismyip.org/automation/n09230945.asp 2>/dev/null); then
		# Extract IP address from HTML
		IP_ADDRESS=$(awk -F'<|: +' '{print $(NF-2)}'<<<"$IP_ADDRESS")
	else
		echo "Error: No external website is reachable, unable to obtain external IP address" >&2
		exit 1
	fi
fi

# Test obtained string
if [[ -z "$IP_ADDRESS" ]]; then
	echo "Could not obtain external IP address, got an empty string" >&2
	exit 1
fi

IP_TEST=$($AWK -F'.' '$0 ~ /^([0-9]{1,3}\.){3}[0-9]{1,3}$/ && $1 <=255 && $2 <= 255 && $3 <= 255 && $4 <= 255'<<<"$IP_ADDRESS")

if [[ -z "$IP_TEST" ]]; then
	echo "Error: Obtained string \"$IP_ADDRESS\" is not a valid IP address" >&2
	exit 1
else
	echo "External IP address is $IP_ADDRESS"
fi

exit 0

# EOF
