#!/bin/sh

############################################################
# getextip
#
# Get external IP address (ppp0) via SNMP
#
# WS 20100225
############################################################

host=localhost
community=Mupfel

current=`date '+%s'`

# Get WAN IP address from SNMP
active_int=`snmpwalk -v 2c -c $community $host IP-MIB::ipAdEntIfIndex|sed 's/ /@/g'`
active_int_index=`echo $active_int | awk -F'@' 'BEGIN {RS=" "} {print $NF}'`

for n in $active_int_index; do
	int_name=`snmpwalk -v 2c -c $community $host IF-MIB::ifDescr.${n} | awk '/ppp[0-9]/ {print $NF}'`
	if [ ! "$int_name" == "" ]; then
		ip=`echo $active_int | awk -F'IfIndex.|@=' 'BEGIN {RS=" "} /'"$n"'$/ {print $2}'`
	fi
done

# If ppp0 is not found, report it as down
if [ "$ip" == "" ]; then
	echo "External interface is down"
	exit 0
else
	echo "External IP address is $ip"
fi

exit 0

# EOF
