#!/bin/bash

############################################################
# getextip_web
# Obtains external IP address via Internet
#
# WS 20110326
############################################################
########## Changes ##########
####
# Errors are printed to stderr now
# WS 20110407
####
# Made the script more portable, it uses either wget or curl
# and takes into account different versions of awk (can be run
# on a Mac now)
# WS 20110418
####
# Used showip.net instead of dyndns.org because dyndns.org
# returns the local instead of the external IP address when
# using a proxy
# WS 20110420
####


AWK=
CURL=
WGET=
get=
ip_address=
ip_test=

# Look for awk
if ! AWK=$(which awk 2>/dev/null); then
	echo "Could not find awk, bailing out." 1>&2
	exit 1
else
	# If we have the GNU version, we need --reinterval
	if $AWK --version | grep -q GNU; then
		AWK="$AWK --re-interval"
	fi 
fi

# Look for wget or curl
if WGET=$(which wget 2>/dev/null); then
	get="$WGET --no-cache -q -O - -t 1 -T 10"
else
	if CURL=$(which curl 2>/dev/null); then
		get="$CURL -s --retry 1 --connect-timeout 10"
	else
		echo "Couldn't find wget or curl, bailing out." 1>&2
		exit 1
	fi
fi

#### Here we go
# Get IP address
if ip_address=$($get http://showip.net/ 2>/dev/null); then
	# Extract IP address from HTML
	ip_address=$(echo "$ip_address" | awk -F\" '/check_ip/ && /value=/ {print $(NF-1)}')
else
	if ip_address=$($get http://www.whatismyip.org/automation/n09230945.asp 2>/dev/null); then
		# Extract IP address from HTML
		ip_address=$(echo "$ip_address" | awk -F'<|: +' '{print $(NF-2)}')
	else
		echo "Error: No external website is reachable, unable to obtain external IP address" 1>&2
		exit 1
	fi
fi

# Test obtained string
if [ -z $ip_address ];then
	echo "Could not obtain external IP address, got an empty string" 1>&2
	exit 1
fi

ip_test=$(echo "$ip_address" | $AWK -F'.' '$0 ~ /^([0-9]{1,3}\.){3}[0-9]{1,3}$/ && $1 <=255 && $2 <= 255 && $3 <= 255 && $4 <= 255')
if [ -z $ip_test ]; then
	echo "Error: Obtained string \"$ip_address\" is not a valid IP address" 1>&2
	exit 1
else
	echo "External IP address is $ip_address"
fi

exit 0

# EOF
