#!/bin/bash

############################################################
# mysql_dump
#
# Dump all MySQL databases to separate files in $BACKUPDIR
#
# WS 20100101
############################################################

########### Configure here ###########
BACKUPDIR=/var/lib/mysql/backup
DB_USER=$1
######### Configuration end ##########

RC=0
DATABASES=
DB_ERR=

# Return code 3 if script is interrupted
trap 'exit 3' 1 2 3 15

usage() {
cat <<END

${0##*/} dumps all MySQL databases to separate files in $BACKUPDIR

Usage: ${0##*/} <database_user>

END
}

# We need a database user
if [[ $# != 1 ]]; then
	echo "Please provide a database user" >&2
        usage >&2
        exit 2
fi

# Test if database is accessible
if ! DATABASES=$(mysql -u "$DB_USER" <<<"show databases" 2>/dev/null | egrep -v 'Database|information_schema' 2>/dev/null); then
	echo "Could not access MySQL databases" >&2
	exit 1
fi

# Dump databases to individual files
for DB in $DATABASES; do
	if ! (mysqldump -u "$DB_USER" "$DB" > "${BACKUPDIR}/${DB}.sql") 2>/dev/null; then
		((RC++))
		DB_ERR="${DB_ERR}${DB}\n"
	fi

done

# Error report
if [[ $RC != 0 ]]; then
	if [[ $RC = 1 ]]; then
		DB_ERR=$(sed 's/\\n//g' <<<"$DB_ERR")
		cat << END >&2
An error occured while dumping the databases.
Database \"$DB_ERR\" could not be dumped.
END
	else
		cat <<END >&2
There were errors while dumping the databases.
The following databases could not be dumped:
$(echo -e $DB_ERR)
END
	fi
fi

exit $RC

# EOF
