#!/bin/sh

############################################################
# psgrep
#
# Greps the process list for a given string
# The search is not case sensitive
#
# WS 20091211
############################################################

ps -ef | grep -i -- "$(sed -r 's/[[:alnum:]]/[&]/'<<<"$1")"

# EOF
