#!/bin/bash

############################################################
# show_start_order
# show_stop_order (symbolic link)
#
# Shows start or stop order of daemons configured to start
# in runlevel 3
#
# WS 20091219
############################################################
########## Changes ##########
####
# Errors are printed to stderr now
# WS 20110408
####
# sh -> bash, no temporary files
# WS 20110416
####


LC_ALL=C
column=1
rc=0
d=
d1=
list=
all_daemons=
started_daemons=

# Set exit code to 2 on abort
trap 'exit 2' 1 2 3 15

if ! cd /etc/rc.d/init.d &> /dev/null; then
	echo "Could not change into /etc/rc.d/init.d, bailing out." >&2
	exit 1
fi

# Let's see how we were called
case ${0##*/} in
	show_start_order)
		column=1 ;;
	show_stop_order)
		column=0 ;;
	*)
		echo "Couldn't recognise my own name (\"${0##*/}\"), bailing out" >&2
		exit 1
		;;
esac

# Get start/stop priority of all files in /etc/init.d
all_daemons=$(awk -F':| +|\t+' '/chkconfig:/ {print $(NF-'"$column"'), FILENAME}' *)

# Get all daemons configured for starting/stopping in runlevel 3
started_daemons=$(chkconfig --list | awk '/3:on/ {print $1}')

for d in $started_daemons ; do
	d1=$d
	d=$(grep $d'$' <<<"$all_daemons")

	if [[ "$d" == "\n" || -z "$d" ]]; then
		echo "Testing \"$d1\" failed" >&2
		rc=1
	fi

	list="${list}${d}\n"
done

echo -e $list | sed -e '/^\w*$/d' | sort -n

exit $rc

# EOF
