#!/bin/sh

############################################################
# switch_gateway
#
# Switches from one default gateway to another
#
# WS 20101104
############################################################

########### Configure here ###########
# Two gateways
gw1="1"
gw2="10"

# Common part of the gateways' IP address
prefix="192.168.10."
######### Configuration end ##########

rc=0
gw_new=

# Get current gateway
gw_current=`route -n | awk '-F\\\.| +' '/^0\.0\.0\.0/ {print $8}'`

# Which gateway is active currently?
if [ "$gw_current" -eq "$gw1" -o "$gw_current" -eq "$gw2" ]; then
	echo "Found gw ${prefix}${gw_current}"

	if [ "$gw_current" -eq "$gw2" ]; then
		gw_new=$gw1
	else
		gw_new=$gw2
	fi

else
	echo "No valid gateway found" 1>&2
	exit 2
fi
		
#### Here we go
echo "Adding gw ${prefix}${gw_new}"
if route add default gw ${prefix}${gw_new} > /dev/null 2>&1; then
	echo "Deleting gw ${prefix}${gw_current}"
	if ! route delete default gw "${prefix}${gw_current}" > /dev/null 2>&1; then
		echo "Could not delete old default gateway ${prefix}${gw_current}" 1>&2
		rc=1
	fi
else
	echo "Could not add new default gateway ${prefix}${gw_new}" 1>&2
	rc=1
fi

echo
route -n

exit $rc

# EOF
